### ISSUE TITLE
spago run: Print compilation messages to stderr 

### ISSUE THREAD

**Issue by Profpatsch** [spacchetti/spago#341] opened 2019-07-29 14:55 UTC
`spago run` should be the same as running the program manually, meaning it shouldn’t print build information to `stdout`, but `stderr`.

Related: spacchetti/spago#256

**Comment by f-f** [comment] 2019-07-29 14:59
Yup, this is a duplicate of #316 which we closed to consolidate everything in #256 (so I'll close this one too and refer you to https://github.com/spacchetti/spago/issues/256#issuecomment-513116049 which includes an updated summary)

ETA for that one: soon, since it's one of the last blockers left for 1.0

**Closed by f-f** 2019-07-29 14:59 UTC
