### ISSUE TITLE
Is it possible to turn off autoformatting?

### ISSUE THREAD

**Issue by joneshf** [spacchetti/spago#300] opened 2019-07-03 03:14 UTC
It looks like every time `spago` runs, it reformats the Dhall file. Is there a way to tell `spago` not to format the files when it runs?

**Comment by f-f** [comment] 2019-07-03 09:26
@joneshf what kind of issue are you having with the autoformatting?

From the Slack channel it looks like the problem is that Spago uses a non-default format command. So would it be enough to document that we autoformat with `dhall --ascii format`?

**Comment by joneshf** [comment] 2019-07-03 14:14
Nah, the issue isn't the output of formatting. `spago` always formatting is causing issues with other tooling.

**Comment by f-f** [comment] 2019-07-03 14:27
Could you detail the usecase some more?

**Comment by joneshf** [comment] 2019-07-03 14:40
We use `make` as the build system because we build more than just PureScript. One of the rules deep in the graph depends on `spago.dhall`. Whenever we run `spago`, it seems to change `spago.dhall` which causes a ton of dependent rules to fire.

I'm not looking to turn off formatting for everyone all the time. But for us, it would be great if we could turn it off when we need to.

**Comment by f-f** [comment] 2019-07-03 15:36
@joneshf right, good point. I believe a good solution here could be to check if the file is formatted (with `dhall format --check`, which IIRC was introduced for exactly this usecase) and then only format it if necessary

**Comment by joneshf** [comment] 2019-07-04 01:23
Hmm, I dunno. That might help for that one rule, but it doesn't sound it would fix that one rule. Instead of the rule firing each run, it would fire at most two times each time `spago.dhall` is unformatted. More to the point, there are other rules that can fire and force everything to be rebuilt the next time around. Checking if a file is formatted first seems like it would address the symptom and not the problem. I guess what I'm saying is that even if you did make the change to check formatting before formatting anyway, we'd still have to work around the fact that `spago` is formatting at all because we can't get an idempotent build otherwise.

Taking a step back, it's a bit unexpected that `spago` is formatting the file at all when you run `spago install` or `spago sources` or something. From the perspective of not needing to install `dhall`, it makes sense. But, I dunno how many people expect `spago` to format a file when installing dependencies. I don't say this to sway your opinion. More to provide an outside perspective.

Again, not looking to change the default for everyone. We've already worked around this issue, so it's not a make or break thing. But, it would simplify our build system if we could pass in a flag instead of altering our rules.

**Comment by f-f** [comment] 2019-07-04 14:34
Yeah, makes sense. Let's add a global `--no-config-format` flag then

**Comment by aniketd** [comment] 2019-07-05 19:08
Opened #302 . Please help with review.

**Comment by LiamGoodacre** [comment] 2019-07-27 09:25
The above PR is merged, should this ticket be closed?

**Comment by f-f** [comment] 2019-07-27 11:17
@LiamGoodacre: upon further investigation I realized that the "autoformatting" is happening because we're trying to migrate old configs without checking if they are using the old schema - this is effectively idempotent except it reformats the file

So I think we should get rid of the flag and just write the file if it's effectively needed (that is, Spago doesn't want to reformat your files, but it will need to in some cases, and we cannot have a flag to shut this behaviour of it's needed to proceed)

However before doing this I'm waiting on #301, as that's shuffling some very relevant code

**Comment by LiamGoodacre** [comment] 2019-07-27 11:27
That makes sense, thanks!

**Comment by f-f** [comment] 2019-07-27 12:25
You're welcome 🙂

Note: I'll fix this before the new release (happening any day now)

**Comment by joneshf** [comment] 2019-07-27 19:34
Shouldn't it be possible to read an old version without also writing the file out?

**Comment by f-f** [comment] 2019-07-27 19:54
@joneshf yes, this is what will happen after 1.0: we'll either not change the config format or just read the files in old config formats

However while we are in "pre-1.0" I'd like to migrate config files to the newest version as mush as we can, so we can deprecate old config formats (and the migration logic itself) and have our "breaking releases" not be distruptive for users

**Closed** 2019-07-29 13:25 UTC
Labels: defect, good first issue, help wanted
