### ISSUE TITLE
Command/dhall to add a package from pursuit?

### ISSUE THREAD

**Issue by googleson78** [spacchetti/spago#375] opened 2019-08-13 13:38 UTC
Sorry if this is something resolved/not the right place to ask!

It's very common in Stack-land to have to use a package from Hackage instead of Stackage - and you can easily do that by just specifying a package name and version in your `stack.yaml`. However with `spago` I could only find the [`mkPackage`](https://raw.githubusercontent.com/purescript/package-sets/psc-0.13.2-20190725/src/mkPackage.dhall) dhall function for adding "custom" packages to my package set.

Would it be desirable (or does it already exist?) to have the ability (a subcommand for example?) to easily add packages from Pursuit to your current package set? Or something that queries Pursuit and automatically generates the `mkPackage` invocation for you.

**Comment by f-f** [comment] 2019-08-13 13:40
@googleson78 I believe this might be a duplicate of #24?

**Comment by googleson78** [comment] 2019-08-13 13:44
Thanks!

I don't really understand how Pursuit interacts with `bower` (as in does it hard depend on it) too well, so if you think it is you're probably right. (and also feel free to close, sorry!)

**Comment by f-f** [comment] 2019-08-13 13:58
In short: Bower is the closest thing we have to a "registry", keeping track of versions of packages. Pursuit is only a place where documentation is uploaded following the tags in Bower, but doesn't contain any actual packages

So if there's a place where we should add packages from that would be Bower (as detailed in that issue)

I'll close, but let's reopen if you feel like what you're searching for is something different from #24 🙂

**Closed by f-f** 2019-08-13 13:58 UTC
