### ISSUE TITLE
Allow integration with atom-ide-purescript

### ISSUE THREAD

**Issue by Dretch** [spacchetti/spago#63] opened 2019-01-01 12:27 UTC
I use Atom to write Purescript source code.

When I converted my project from Pulp + Bower to Spago the nice features of Atom (show-type-on-hover, go-to-definition, auto-import, etc) stopped working.

It would be nice to get this working again. I am not sure entirely what is involved, or whether changes are required to https://github.com/nwolverson/atom-ide-purescript itself. One thing that does appear to be required is for `spago build` to pass through arguments to `purs`, like `pulp build -- --json-errors` (once this is done then atom-ide can at least be configured to build with Spago).

**Comment by justinwoo** [comment] 2019-01-01 13:39
i think what you're missing is that the language server that's running doesn't know where to find sources. you probably want to open an issue in atom-ide-purescript about providing a way to call a command to get psc-package style sources, so that you can use `spago sources` to get the source globs.

**Comment by f-f** [comment] 2019-01-01 19:13
From a cursory look at the `atom-ide-purescript` codebase, it looks like Justin is on point about the plugin not finding the right source globs. Though I'm not sure we have to use `spago sources` for this: it looks like the default value for the source globs points to the bower cache ([here](https://github.com/nwolverson/atom-ide-purescript/blob/db17126e4f66462b4db4af07a2a516a0e86047eb/src/IdePurescript/Atom/Config.purs#L24)), but this is configurable by setting `ide-purescript.pscSourceGlob` ([see here](https://github.com/nwolverson/atom-ide-purescript/blob/db17126e4f66462b4db4af07a2a516a0e86047eb/src/IdePurescript/Atom/Config.purs#L35)).

So I guess setting it to something like `["src/**/*.purs", ".spago/**/*.purs"]` might work?

**Comment by justinwoo** [comment] 2019-01-01 20:46
For the most part, you should be able to use `.spago/*/*/src/**/*.purs` for the sources of your dependencies. If you run into problems with conflicting module definitions with this, you could clean your .spago directory and try again.

**Comment by f-f** [comment] 2019-01-06 13:14
Update: once #66 goes in it would be possible to run `spago build -- --json-errors`, so the only thing remaining to fix for this issue would be to update `atom-ide-purescript` to run `spago sources`

**Comment by Dretch** [comment] 2019-01-19 16:44
#66 is in (thanks!), so it is now possible to run `spago build -- --json-errors`. I have found a new problem, however: `spago build` dies unless the `HOME` environment variable is defined (Dhall needs it to find its cache directory), but purescript-language-server does not pass `HOME` through (see https://github.com/nwolverson/purescript-language-server/issues/44).

I also have not managed to get go-to-definition to work, and I don't know why (my purescript source glob is set to `src/**/*.purs, bower_components/**/*.purs, .spago/*/*/src/**/*.purs`).

**Comment by f-f** [comment] 2019-01-19 17:07
@Dretch oh wow, I think this is a Dhall bug, opened https://github.com/dhall-lang/dhall-haskell/issues/788

On the other hand, if Dhall is not able to find a place to cache imports, your package-set will have to be fetched from GitHub every time the atom plugin tries to build (so e.g. you won't be able to build while offline), so you would really want the plugin to pass `HOME` to subcommands

**Comment by f-f** [comment] 2019-01-20 22:07
@spicydonuts fix for that should be up in #82 

Though I'm not sure how much of a fix this is. E.g. in case of build success we do output "Build successful" after the purs output. Is that fine? (see [this line](https://github.com/spacchetti/spago/pull/82/files#diff-e4b0ddff672e425817534d26e4aedf3dR269))

**Comment by spicydonuts** [comment] 2019-01-21 21:19
I'm not 100% sure but I thought the entire output had to be parseable as JSON

**Comment by f-f** [comment] 2019-01-21 21:22
This is weird, because here in the [language-server](https://github.com/nwolverson/purescript-language-server/blob/master/src/IdePurescript/Build.purs#L80) there's an `Array.partition` for lines that begin with json, so even the current version should not have any issue 🤔

**Comment by f-f** [comment] 2019-01-22 09:51
@Dretch the issue of spago dying when `HOME` is not set is now fixed in master, I'll make a release today or tomorrow if it's ok (I'd like to figure out this VSCode thing so we ship all the fixes together)

**Comment by nwolverson** [comment] 2019-01-23 16:12
RE language-server and junk in the JSON output - no, it should only matter that the JSON output is (unprefixed) on a single line on stderr, as per compiler or pulp output, both of which already include junk lines too. Nate did have some issue on a "real world" project which we couldn't reproduce so maybe there is some issue around there though.

(On the other points in this integration - I'll need to find some time but will address the `spago sources` command & checking env variables are passed through)

**Comment by f-f** [comment] 2019-02-10 21:52
@Dretch @nwolverson I think with the latest version of `purescript-language-server` (0.12.7) and the latest version of `spago` (0.6.4) this issue can be considered fixed, right?

**Comment by Dretch** [comment] 2019-02-12 20:06
@f-f I think a new release of `atom-ide-purescript` is needed before this is considered completely fixed.

**Comment by JordanMartinez** [comment] 2019-03-07 02:10
Just checking in on the status of this issue. 

It's been 22 days since the last comment and I don't see a new release for `atom-ide-purescript`. I'm assuming this issue hasn't been fixed yet, correct?

**Comment by nwolverson** [comment] 2019-03-07 07:41
I just pushed a release of `atom-ide-purescript` (finally)

**Comment by f-f** [comment] 2019-03-07 07:49
Wonderful! It looks like we can close this one, but feel free to comment here if there are more issues and this needs to be reopened

Thanks a lot @nwolverson, @Dretch and everyone involved! 👏

**Closed by f-f** 2019-03-07 07:49 UTC
