### ISSUE TITLE
Hitting Ctrl-C in "spago repl" messes up prompt (cmd.exe, powershell.exe)

### ISSUE THREAD

**Issue by kohanyirobert** [spacchetti/spago#483] opened 2019-11-06 10:54 UTC
Having opened up a new `cmd` shell and starting `spago repl` in a simple project if I hit <kbd>Ctrl-c</kbd> something brokes ... the REPL exits, but after that if I restart it in the same `cmd` session my input gets mangled and garbled.

Instead if I do this

`purs repl "src\**\*.purs" ".spago\*\*\src\**\*.purs"`

all is fine. <kbd>Ctrl-C</kbd> clears the current line and keeps things running, and most importantly the shell's input doesn't break. (Same things happen in `cmd.exe` and `powershell.exe`.

(Not sure if this makes sense or not, I'll try to make a little demo of this somehow when I got the time.)

**Comment by f-f** [comment] 2019-11-06 11:38
Thanks for the report @kohanyirobert!

@stkb any idea why this might be happening?

**Comment by kohanyirobert** [comment] 2019-11-06 15:43
One bit of extra info. I tried to define an `npm` script in my `package.json` which executes this: `purs repl "src\**\*.purs" ".spago\*\*\src\**\*.purs"` but it has the same issue as running `spago repl`, so I guess the issue relates to subprocesses created in a not so correct way for Windows to handle or something.

**Comment by stkb** [comment] 2019-11-06 18:54
I had noticed this before but my experience is a bit different. For me it doesn't matter whether you run `purs repl` through Spago or directly, the issue is the same and seems to lie with purs.exe.

I'll describe what I see on my machine. This just running from standard cmd.exe and purs v13.4:

```
spago init
spago install psci-support
purs repl "src\**\*.purs" ".spago\*\*\src\**\*.purs"
```

The repl starts and creates a process tree looking like this:
```
cmd.exe
 ↳ purs.exe (1)
    ↳ purs.exe (2)
```
The `purs.exe` (2) process uses a fair bit of CPU by the way, even when the repl is idle.

For me however, ctrl-c always exits, and goes back to the command prompt. The `purs.exe` (1) process terminates, however the `purs.exe` (2) process stays hanging around, 'orphaned'. This will only be cleaned up by closing the command window, so if you continually start and the quit the repl with ctrl-c, a number of these processes will build up. (Quitting with `:quit` cleans everything [from that session] up fine)

So assume we've run the repl once, quit with ctrl-c, and still have an old `purs.exe` process running. After running the repl again, we get the problem with only some keystrokes registering:
```
> import Prelude
Error found:
in module $PSCI
at :1:1 - 1:4 (line 1, column 1 - line 1, column 4)

  Unknown value ior
```

So a workaround is: I've found that if you go and terminate the old `purs.exe` process that's still running, that fixes the input problem. Though I had mixed experience with this: one time killing the old process fixed it immediately, another time I had to restart the repl before it worked properly again.

As I say, for me it doesn't matter if you run the repl through Spago or not. The only difference is that the process tree then looks like this:
```
cmd.exe > spago.exe > cmd.exe > purs.exe > purs.exe
```
But the rest is the same

**Comment by kohanyirobert** [comment] 2019-11-06 20:27
What @stkb says. I've verified the same happens on my end. When I've executed `purs repl ...` I didn't have `purs.bin` processes running around aimlessly so I didn't notice this. Anyway, using `purs repl ...` from the get-go keeps things behaving nice.

**Comment by f-f** [comment] 2019-11-07 16:59
@stkb thanks for looking into this, wonderful analysis! 👏 

So it looks like this is not a Spago issue (i.e. I'm not sure we can even work around this), so should we open an issue in [the `purs` repo](https://github.com/purescript/purescript)?

**Comment by f-f** [comment] 2019-11-07 17:52
Oh, it looks like Pulp has a similar issue open: https://github.com/purescript-contrib/pulp/issues/342

**Comment by kohanyirobert** [comment] 2019-11-07 20:47
When I said that "I've verified the same happens on my end" as @stkb described what I meant that running `purs repl ...` directly _after_ I already run `spago repl` and exited with a <kbd>Ctrl-c</kbd> behaves incorrectly, but running only `purs repl ...` is fine. So, essentially, what I observe is different, sorry for the confusion, let me further explain.

1. I verify that I have no `purs.bin` processes.
1. Then I run `purs repl ...`, this is how the process tree looks for me
    ```
    cmd.exe
     ↳ purs.exe
    ```
    (Plus there's a `conhost.exe` under `cmd.exe`.)
1. Whatever I do at this point everything is perfectly fine. <kbd>Ctrl-c</kbd> and <kbd>Ctrl-d</kbd> works as expected, the latter terminates the `purs.bin` process nicely (just as `:quit`).

Now with `spago repl` this is what happens.

1. I verify that I have no `purs.bin` processes.
1. I run `spago repl`, this is the process tree
    ```
    cmd.exe (1)
     ↳ node.exe
         ↳ spago.exe
             ↳ cmd.exe (2)
                 ↳ `purs.exe`
    ```
    (Plus there's a `conhost.exe` under the first `cmd.exe`.)
1. If I hit <kbd>Ctrl-c</kbd> then the second `cmd.exe` gets orphaned the path of processes above this are terminated so I'm left with this.
    ```
    cmd.exe (2)
     ↳ purs.exe
    ```
1. After this even if I start the REPL with `spago repl` or `purs repl ...` keystrokes aren't registered correctly. Killing `purs.bin` seems to fix things ... haven't experimented with that too much (don't see the point).

**Note**: I also experience a huge amount of CPU activity for the `purs.bin` process even if I do nothing.

**Comment by stkb** [comment] 2019-11-11 10:07
Apologies, the behavior I described above is wrong and was related to my setup.

@kohanyirobert Thanks for the full description: I can now corroborate what you say (though I think you mean `purs.bin` in your examples? You have a `purs.bin` if you install PureScript via npm; `purs.exe` if you use the direct download.

I was also using a compiled `spago.exe` file directly rather than the NPM installation, which is why I wasn't seeing any difference re: using `spago repl` or `purs repl ...`.

I think if you download and use the `spago.exe` from releases, rather than the NPM installation, then `spago repl` will work fine for you?

So just to reiterate, the problem seem to be with the NPM installation, not with purs, nor the spago binary itself. I'm pretty sure it's with our node/javascript shim `npm/spago` that's used for the windows NPM/Yarn installations. That shim isn't handling the Ctrl-C/SIGINT signal, so is getting terminated and leaving an orphan process.

Naturally this needs fixing so I'll look into that.

**Comment by stkb** [comment] 2019-11-11 10:56
Seem to have found the fix, so PR will be coming soon

**Closed** 2019-11-11 12:54 UTC
Labels: defect, help wanted, windows

**Comment by kohanyirobert** [comment] 2019-11-11 20:25
@stkb Yep, when I wrote `purs.exe` I meant `purs.bin` and I indeed use the `npm` version of `spago` and `purs`. Cool if this is fixed! Don't have time to try out the binaries, I'll be on the lookout for the new release, but I'm pretty sure this fixes it. Thanks big time! 👍
